-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, 
       MONTH(SALES_DATE) AS MONTH,
       COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS,
       ROUND(COUNT(DISTINCT A.USER_ID) / (SELECT COUNT(USER_ID)
                                       FROM USER_INFO
                                       WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM USER_INFO A
JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE YEAR(A.JOINED) = 2021
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
ORDER BY YEAR ASC, MONTH ASC
       
# SELECT YEAR(SALES_DATE) AS YEAR,
#        MONTH(SALES_DATE) AS MONTH,
#        COUNT(DISTINCT(a.USER_ID)) AS PUCHASED_USERS,
#        ROUND(COUNT(DISTINCT a.USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_INFO WHERE YEAR(JOINED) = 2021) , 1) AS PUSHASED_RATIO
# FROM USER_INFO AS a INNER JOIN ONLINE_SALE AS b USING(USER_ID)
# WHERE YEAR(JOINED) = 2021
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY 1 ASC, 2 ASC