SELECT YEAR(A.SALES_DATE) AS YEAR, MONTH(A.SALES_DATE) AS MONTH,
COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS,
ROUND((COUNT(DISTINCT A.USER_ID)/(SELECT COUNT(USER_ID) FROM USER_INFO
                   WHERE JOINED LIKE '2021%')),1) AS PUCHASED_RATIO
FROM ONLINE_SALE A
JOIN USER_INFO B ON A.USER_ID = B.USER_ID
WHERE B.JOINED LIKE '2021%'
GROUP BY MONTH
ORDER BY YEAR ASC, MONTH ASC