SELECT HISTORY_ID, 
ROUND((((DATEDIFF(END_DATE, START_DATE))+1)*DAILY_FEE)
   *(CASE 
     WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 then 1
     WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 then 0.95
     WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 then 0.92
     ELSE 0.85 END)) AS FEE
 FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC


# SELECT HISTORY_ID, 
#     round(DAILY_FEE * (DATEDIFF(h.END_DATE,h.START_DATE)+1)
#     * (case 
#     when DATEDIFF(END_DATE,START_DATE)+1 < 7 then 1
#     when DATEDIFF(END_DATE,START_DATE)+1 < 30 then 0.95
#     when DATEDIFF(END_DATE,START_DATE)+1 < 90 then 0.92
#     else 0.85 end)) as "FEE"

# from CAR_RENTAL_COMPANY_CAR as c 
#     join CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
#     on c.CAR_ID = h.CAR_ID
#     join CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p
#     on c.CAR_TYPE = p.CAR_TYPE

# where c.car_type = "트럭"

# group by HISTORY_ID

# order by FEE desc , HISTORY_ID desc

# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# 5 8 15