# -- 코드를 작성해주세요
# SELECT * FROM DEVELOPERS A
# # JOIN SKILLCODES B ON A.SKILL_CODE = B.CODE
# # ORDER BY A.ID

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME FROM SKILLCODES A
JOIN DEVELOPERS B
WHERE CATEGORY = 'Front End' and SKILL_CODE & CODE = CODE
ORDER BY ID