# -- 코드를 입력하세요
# SELECT CATEGORY, COUNT(SALES) AS TOTAL_SALES FROM BOOK A, BOOK_SALES B
# WHERE A.BOOK_ID = B.BOOK_ID AND SALES_DATE LIKE '2022-01%'
# GROUP BY CATEGORY
# ORDER BY CATEGORY ASC
SELECT 
CATEGORY, SUM(SALES) TOTAL_SALES

FROM BOOK B,BOOK_SALES S

WHERE B.BOOK_ID= S.BOOK_ID AND
SALES_DATE LIKE "2022-01%"

GROUP BY CATEGORY

ORDER BY CATEGORY